server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.5.81.227:3306/sakila?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: /html

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    cn:
      ncut:
        flinkserver:
          dao: debug